export default {
  GET_SINGLE_SYMBOL: 'GET_SINGLE_SYMBOL',
  SINGLE_SYMBOL_SUCCESS: 'SINGLE_SYMBOL_SUCCESS',
  SINGLE_SYMBOL_FAILURE: 'SINGLE_SYMBOL_FAILURE',
  GET_TOP_LIST: 'GET_TOP_LIST',
  TOP_LIST_SUCCESS: 'TOP_LIST_SUCCESS',
  TOP_LIST_FAILURE: 'TOP_LIST_FAILURE',
  GET_HISTORICAL_DATA_FOR_SYMBOL: 'GET_HISTORICAL_DATA_FOR_SYMBOL',
  HISTORICAL_DATA_SUCCESS: 'HISTORICAL_DATA_SUCCESS',
  HISTORICAL_DATA_FAILURE: 'HISTORICAL_DATA_FAILURE'
}
