export default {
  GET_SINGLE_SYMBOL: 'GET_SINGLE_SYMBOL',
  SINGLE_SYMBOL_SUCCESS: 'SINGLE_SYMBOL_SUCCESS',
  SINGLE_SYMBOL_FAILURE: 'SINGLE_SYMBOL_FAILURE',
  GET_TOP_LIST: 'GET_TOP_LIST',
  TOP_LIST_SUCCESS: 'TOP_LIST_SUCCESS',
  TOP_LIST_FAILURE: 'TOP_LIST_FAILURE'
}
